import time
def infinite_recursion(n):
    if n > 0:
        print(""Recursion number:"", n)
        time.sleep(1)
        infinite_recursion(n+1)
    else:
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Recursion number:"", n)
        time.sleep(1)
        print(""Rec